import numpy as np

CONTROL_HZ = 30
FRAME_FPS = 30
JPEG_QUALITY = 80

ROLL_SCALE = 1.0
PITCH_SCALE = 0.8
YAW_SCALE = 1.3

ROLL_CLIP_RAD = np.deg2rad(35)
PITCH_CLIP_RAD = np.deg2rad(35)
YAW_CLIP_RAD = np.deg2rad(55)

ROTATION_SCALE = np.array([ROLL_SCALE, PITCH_SCALE, YAW_SCALE], dtype=np.float64)
ROTATION_CLIP_RAD = np.array([ROLL_CLIP_RAD, PITCH_CLIP_RAD, YAW_CLIP_RAD], dtype=np.float64)
ROTATION_LIMIT = ROTATION_SCALE * ROTATION_CLIP_RAD

ROTATION_SMOOTHING_ALPHA = 0.35
ROTATION_DEADBAND = 0.03

ANTENNA_CLIP_RAD = np.deg2rad(150)
ANTENNA_CLIP_RANGE = 3
ANTENNA_SMOOTHING_ALPHA = 0.3
ANTENNA_DEADBAND = 0.03

BODY_YAW_LIMIT = np.deg2rad(30)
BODY_YAW_TURN_RATE = np.deg2rad(5)
